apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server-deployment
  labels:
    app: go-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-http
  template:
    metadata:
      labels:
        app: go-http
    spec:
      containers:
      - name: go-server
        image: localhost:32000/go:inbuilt
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
